---
- hosts: localhost
  become: yes
  roles:
    - role: GROG.package
      package_list:
        - name: i3
        - name: pulseaudio-utils
        - name: xbacklight

- hosts: localhost
  tasks:
    - file:
        path: ~/.config
        state: absent
      with_items:
        - .config/i3
        - .config/i3status

    - template:
        src: 'templates/{{ item }}.j2'
        dest: '~/{{ item }}'
      with_items:
        - .config/i3/config
        - .config/i3status/config
